# Generated by Django 3.1.7 on 2021-03-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
